#!/usr/bin/env python3
"""Release helpers used by .github/workflows/*.yml. Standard library only (Python 3.11+).

  version                       print the workspace version from Cargo.toml
  check-tag TAG                 fail unless TAG == v<version> and CHANGELOG has a dated section
  notes VERSION                 print the CHANGELOG section for VERSION
  package TARGET BINARY OUTDIR  build pdfjiff-TARGET.{tar.gz,zip} with the binary, README, licenses
                                and THIRD-PARTY-LICENSES.md (when generated)
  checksums DIR                 write DIR/SHA256SUMS for every other file in DIR
  homebrew VERSION SUMS         print a Homebrew formula for the release
  scoop VERSION SUMS            print a Scoop manifest for the release

Run from the repository root. `python3 -m unittest discover .github/scripts` tests this file.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import json
import os
import re
import sys
import tarfile
import tomllib
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DESCRIPTION = "Fast, private PDF compression, merging and inspection for your terminal"
UNIX_TARGETS = {
    ("macos", "arm"): "aarch64-apple-darwin",
    ("macos", "intel"): "x86_64-apple-darwin",
    ("linux", "arm"): "aarch64-unknown-linux-musl",
    ("linux", "intel"): "x86_64-unknown-linux-musl",
}
WINDOWS_TARGETS = {"64bit": "x86_64-pc-windows-msvc", "arm64": "aarch64-pc-windows-msvc"}
BUNDLED_DOCS = ("README.md", "LICENSE-MIT", "LICENSE-APACHE")
# Generated by cargo-about in the release workflow; bundled whenever present.
NOTICES = "THIRD-PARTY-LICENSES.md"
EPOCH = 315532800  # 1980-01-01: the earliest timestamp a zip entry can hold


class ReleaseError(Exception):
    pass


def workspace_version(root: Path = ROOT) -> str:
    data = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))
    try:
        return data["workspace"]["package"]["version"]
    except KeyError as exc:
        raise ReleaseError("Cargo.toml has no [workspace.package] version") from exc


def repository(root: Path = ROOT) -> str:
    """owner/name, from GITHUB_REPOSITORY in CI or the Cargo repository URL locally."""
    if os.environ.get("GITHUB_REPOSITORY"):
        return os.environ["GITHUB_REPOSITORY"]
    data = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))
    url = data["workspace"]["package"]["repository"]
    match = re.fullmatch(r"https://github\.com/([^/]+/[^/]+?)/?", url)
    if not match:
        raise ReleaseError(f"repository is not a GitHub URL: {url}")
    return match.group(1)


def changelog_section(version: str, text: str) -> tuple[str, str]:
    """Return (heading, body) for `## [version] - date`."""
    pattern = re.compile(rf"^## \[{re.escape(version)}\](?P<rest>[^\n]*)\n(?P<body>.*?)(?=^## \[|^\[[^\]]+\]: |\Z)", re.M | re.S)
    match = pattern.search(text)
    if not match:
        raise ReleaseError(f"CHANGELOG.md has no '## [{version}]' section. Add one before tagging.")
    return match.group(0).splitlines()[0], match.group("body").strip()


def check_tag(tag: str, root: Path = ROOT) -> str:
    version = workspace_version(root)
    if tag != f"v{version}":
        raise ReleaseError(f"tag {tag} does not match the Cargo workspace version {version}; tag v{version} instead")
    manifest = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))
    core = manifest.get("workspace", {}).get("dependencies", {}).get("pdfjiff-core", {})
    if isinstance(core, dict) and core.get("version") not in (None, version):
        raise ReleaseError(
            f"[workspace.dependencies] pdfjiff-core requires version {core['version']}; set it to {version}"
        )
    heading, body = changelog_section(version, (root / "CHANGELOG.md").read_text(encoding="utf-8"))
    if not re.search(r"\d{4}-\d{2}-\d{2}", heading):
        raise ReleaseError(f"set the release date in CHANGELOG.md: '{heading}' -> '## [{version}] - YYYY-MM-DD'")
    if not body:
        raise ReleaseError(f"the CHANGELOG.md section for {version} is empty")
    return version


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def package(target: str, binary: Path, outdir: Path, root: Path = ROOT) -> Path:
    """Reproducible archive: fixed timestamps, owners and modes; one top-level folder."""
    windows = "windows" in target
    exe = "pdfjiff.exe" if windows else "pdfjiff"
    folder = f"pdfjiff-{target}"
    members = [(f"{folder}/{exe}", binary.read_bytes(), 0o755)]
    docs = BUNDLED_DOCS + ((NOTICES,) if (root / NOTICES).is_file() else ())
    members += [(f"{folder}/{name}", (root / name).read_bytes(), 0o644) for name in docs]
    outdir.mkdir(parents=True, exist_ok=True)
    if windows:
        out = outdir / f"{folder}.zip"
        with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as archive:
            for name, data, mode in members:
                info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
                info.external_attr = (0o100000 | mode) << 16
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, data)
        return out
    out = outdir / f"{folder}.tar.gz"
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode="w", format=tarfile.PAX_FORMAT) as archive:
        directory = tarfile.TarInfo(folder)
        directory.type, directory.mode, directory.mtime = tarfile.DIRTYPE, 0o755, EPOCH
        archive.addfile(directory)
        for name, data, mode in members:
            info = tarfile.TarInfo(name)
            info.size, info.mode, info.mtime = len(data), mode, EPOCH
            info.uname = info.gname = ""
            archive.addfile(info, io.BytesIO(data))
    with out.open("wb") as handle, gzip.GzipFile(filename="", fileobj=handle, mode="wb", mtime=0) as gz:
        gz.write(raw.getvalue())
    return out


def write_checksums(directory: Path) -> Path:
    files = sorted(p for p in directory.iterdir() if p.is_file() and p.name != "SHA256SUMS")
    if not files:
        raise ReleaseError(f"no files to checksum in {directory}")
    out = directory / "SHA256SUMS"
    out.write_text("".join(f"{sha256(p)}  {p.name}\n" for p in files), encoding="utf-8")
    return out


def read_checksums(path: Path) -> dict[str, str]:
    sums = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) == 2:
            sums[parts[1].lstrip("*")] = parts[0].lower()
    return sums


def _require(sums: dict[str, str], name: str) -> str:
    if name not in sums:
        raise ReleaseError(f"SHA256SUMS has no entry for {name}")
    return sums[name]


def homebrew_formula(version: str, sums: dict[str, str], repo: str) -> str:
    base = f"https://github.com/{repo}/releases/download/v{version}"
    blocks = []
    for os_name in ("macos", "linux"):
        inner = []
        for cpu in ("arm", "intel"):
            archive = f"pdfjiff-{UNIX_TARGETS[(os_name, cpu)]}.tar.gz"
            inner.append(
                f"    on_{cpu} do\n"
                f'      url "{base}/{archive}"\n'
                f'      sha256 "{_require(sums, archive)}"\n'
                f"    end"
            )
        blocks.append(f"  on_{os_name} do\n" + "\n".join(inner) + "\n  end")
    joined = "\n\n".join(blocks)
    return f'''# Generated by the PDFJiff release workflow ({repo}). Do not edit by hand.
class Pdfjiff < Formula
  desc "{DESCRIPTION}"
  homepage "https://github.com/{repo}"
  version "{version}"
  license any_of: ["MIT", "Apache-2.0"]

{joined}

  def install
    bin.install "pdfjiff"
    generate_completions_from_executable(bin/"pdfjiff", "completions", shells: [:bash, :zsh, :fish, :pwsh])
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/pdfjiff --version")
    assert_match '"network_required":false', shell_output("#{{bin}}/pdfjiff capabilities --json")
  end
end
'''


def scoop_manifest(version: str, sums: dict[str, str], repo: str) -> str:
    base = f"https://github.com/{repo}/releases/download/v{version}"
    architecture, autoupdate = {}, {}
    for key, target in WINDOWS_TARGETS.items():
        archive = f"pdfjiff-{target}.zip"
        architecture[key] = {
            "url": f"{base}/{archive}",
            "hash": _require(sums, archive),
            "extract_dir": f"pdfjiff-{target}",
        }
        autoupdate[key] = {
            "url": f"https://github.com/{repo}/releases/download/v$version/{archive}",
            "extract_dir": f"pdfjiff-{target}",
        }
    manifest = {
        "version": version,
        "description": DESCRIPTION,
        "homepage": f"https://github.com/{repo}",
        "license": "MIT|Apache-2.0",
        "architecture": architecture,
        "bin": "pdfjiff.exe",
        "checkver": {"github": f"https://github.com/{repo}"},
        "autoupdate": {"architecture": autoupdate, "hash": {"url": "$baseurl/SHA256SUMS"}},
    }
    return json.dumps(manifest, indent=4) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("version")
    sub.add_parser("check-tag").add_argument("tag")
    sub.add_parser("notes").add_argument("version")
    pkg = sub.add_parser("package")
    pkg.add_argument("target")
    pkg.add_argument("binary", type=Path)
    pkg.add_argument("outdir", type=Path)
    sub.add_parser("checksums").add_argument("directory", type=Path)
    for name in ("homebrew", "scoop"):
        manifest = sub.add_parser(name)
        manifest.add_argument("version")
        manifest.add_argument("sums", type=Path)
        manifest.add_argument("--repo")
    args = parser.parse_args(argv)
    try:
        if args.command == "version":
            print(workspace_version())
        elif args.command == "check-tag":
            print(check_tag(args.tag))
        elif args.command == "notes":
            print(changelog_section(args.version, (ROOT / "CHANGELOG.md").read_text(encoding="utf-8"))[1])
        elif args.command == "package":
            print(package(args.target, args.binary, args.outdir))
        elif args.command == "checksums":
            print(write_checksums(args.directory))
        else:
            version = args.version.removeprefix("v")
            render = homebrew_formula if args.command == "homebrew" else scoop_manifest
            sys.stdout.write(render(version, read_checksums(args.sums), args.repo or repository()))
    except (ReleaseError, OSError, tomllib.TOMLDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
